### ISSUE TITLE
Placeholder text if repo description doesn't exist

### ISSUE THREAD

**Issue by LennyLizowzskiy** [sapondanaisriwan/Repositories-Grid-For-GitHub#2]
Referencing this issue: https://github.com/sapondanaisriwan/Repositories-Grid-For-GitHub/issues/1
In addition to fix the blank space in between
//

So it will look like this

![image](https://github.com/sapondanaisriwan/Repositories-Grid-For-GitHub/assets/46971551/a796025e-7766-4991-b65c-465857897000)

**Comment by sapondanaisriwan** [comment]
hmm, I'm not sure CSS can do that 🤔

**Comment by LennyLizowzskiy** [comment]
Oh, I forgot about that. Can you do alignment to the bottom then please? I think I can change the text via Tampermonkey userscript

**Comment by sapondanaisriwan** [comment]
![image](https://github.com/sapondanaisriwan/Repositories-Grid-For-GitHub/assets/64634605/6f1f9cc4-0cb1-4228-b98c-de1005f9f800)
![image](https://github.com/sapondanaisriwan/Repositories-Grid-For-GitHub/assets/64634605/39f08a36-eff2-4686-abfd-f1bab25732c3)
